### ISSUE TITLE
Getting the Joystick to run

### ISSUE THREAD

**Issue by ghost** [strands-project/autonomous_patrolling#1]
Get the Joystick box opened. 

Adapt code to work with ROS and with the simulator

**Comment by marc-hanheide** [comment]
Maybe you know all this already, but there is a standard ROS "joy" node that publishes all joystick data on a topic. All that is needed is a small program converts these into Twist messages and publishes them on the  `cmd_vel` topic. I think, turtlebot_teleop can serve as a template for this.

**Comment by ghost** [comment]
Thank you @marc-hanheide, this was mainly for documentation purposes, we are working on this already! :)

**Comment by nilsbore** [comment]
I have written such a node if someone wants it!

**Comment by ghost** [comment]
We implemented this based on @nilsbore's code. Everything seems to be working now, however due to sticky controls in the joypad, we created a Dead man's switch which prevents any actions unless it is pressed. To move the robot with the joypad, keep the left shoulder button pressed and move it with the left joystick. 

For further details see the README.md file in the repo root.
