### ISSUE TITLE
Move rumbelpad control into scito_apps

### ISSUE THREAD

**Issue by cdondrup** [strands-project/autonomous_patrolling#10]
Move the rumblepad_control package into the scitos_apps repo and refactor into scitos_teleop according to pr2_teleop.

**Comment by cdondrup** [comment]
The rumblepad_control can now be removed from this package. Would you like to do it @BFALacerda since you already restructured everything?

**Comment by cdondrup** [comment]
Also the launch files of the map_saver and waypoint_recorder have to be adapted to not contain the call to the rumbelpad any more.

**Comment by bfalacerda** [comment]
Yes, taking care of it now.

**Comment by cdondrup** [comment]
Done. Thank you.
