### ISSUE TITLE
patroller.py and insert_in_db.py need to use message store

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#118]
Waypoints are retrieved and stored as Poses. Since I refactored strands_datacentre, some the utility functions have changed which has broken the way these poses are written to and read from the db. This can be fixed by using the new [message_store.py](https://github.com/strands-project/ros_datacentre/blob/groovy-devel/ros_datacentre/src/ros_datacentre/message_store.py) interface, an example of which can be seen in [the example client](https://github.com/strands-project/ros_datacentre/blob/groovy-devel/ros_datacentre/scripts/example_message_store_client.py). See the [insert method](https://github.com/strands-project/ros_datacentre/blob/groovy-devel/ros_datacentre/src/ros_datacentre/message_store.py#L26) which adds the message along with your meta information. And [query](https://github.com/strands-project/ros_datacentre/blob/groovy-devel/ros_datacentre/src/ros_datacentre/message_store.py#L38) which can query on both message content and meta information,

**Comment by hawesie** [comment]
I can probably do this, but won't have time until Friday at least.

**Comment by hawesie** [comment]
@BFALacerda pull request #120 should add the fixed for this. You will need to re-run the waypoint insert script before running the patroller.

**Comment by bfalacerda** [comment]
closing solved old issues
