### ISSUE TITLE
add recovery behaviours

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/autonomous_patrolling#21]
In the current version, if move_base fails to reach a goal, the patroller simply dies. Recovery behaviours should be added. Two papers from willow's garage that will be useful for this:

http://www.ros.org/wiki/Papers/ICRA2010_Marder-Eppstein

http://www.willowgarage.com/sites/default/files/icra_continuous_ops.pdf

**Comment by marc-hanheide** [comment]
As discussed in the long-term autonomy meeting (23/7/13) we will just
- try a number of times to reach the place and then skip to the next
- if there is no progress or an emergency stop then flag up any issues (e.g. move_base fail) via either
  - twitter, 
  - email
  - or text
- I suggest we create a communication alert node that monitors some strands-specific status topic where we flag any issues (this should then also be monitored in the dashboard? @cburbridge)

**Comment by cburbridge** [comment]
I'll look into this...

**Comment by hawesie** [comment]
What's the current status of this?

**Comment by ghost** [comment]
At our group a guy took it upon himself to extend it with a very basic
recovery behavior. I guess we should make a pull request.

**Comment by bfalacerda** [comment]
There are recovery behaviours for bumper pressing and move_base failing. Right now they are pretty simple, each composed of a  single recovery state, but the states are easy to edit and one can even turn them into small state machines if the need arises.

As suggested in the meeting, when move_base fails a given amount (5) of times when going to a given point, the robot simply gives up on that one and goes to the next. We can add a counter to see how many fails happened,  though that's not implemented at the moment

**Comment by marc-hanheide** [comment]
@AlexanderHermans what kind of behaviours did you implement? And yes, if you are working on an issue or already have contributed to one, raise a pull request or at least leave a comment on an issue when you start working on it. We should try to avoid duplications of efforts.

**Comment by ghost** [comment]
Sorry for the late reply. The last two days were dedicated to seminar
presentations at our chair. :x

So far he just changed the code so that it will not crash and randomly
select a new point to go to. I wasn't sure whether we were going to commit
it, as I am not clear on what the long_term_patroller exactly does. He is
just unstoppable when he sees code he thinks he can do better ;)

He wanted to integrate the battery charging. After that one of us will
raise a pull request.

**Comment by marc-hanheide** [comment]
Hi, 

I believe this functionality is already in place. May I suggest that in the future you liaise with the original author prior to start coding and/or raise an issue that you assign yourself to do that everybody sees what you are working on. We should avoid duplicating work. 

Thanks, Marc

**Comment by hawesie** [comment]
Back to the recovery behaviours! I suggest we close this issue and create new, more specific ones, for the recovery behaviours we have identified the need for.

**Comment by bfalacerda** [comment]
closing this as suggested by @hawesie
