### ISSUE TITLE
implement option to finish patrolling after one full iteration of all points (for CI server test)

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/autonomous_patrolling#24]

**Comment by marc-hanheide** [comment]
Could this be included as a command line option in the long-term patroller? Looks easy, doesn't it @BFALacerda ?

**Comment by bfalacerda** [comment]
yes, though the random point generation will have to be changed. Right now after reaching each point, a new point is chosen randomly, I can change this to make it so the robot randomly chooses a sequence that goes through all the points, and when it completes the sequence, a new one is randomly chosen (or it finishes,depending on the command line argument you mentioned). Is this what you want, @marc-hanheide ?

**Comment by marc-hanheide** [comment]
I guess so ;-) But it's not too urgent. Maybe, there should be an option to indicate the number of iterations, with default infinity.

Makes sense?

**Comment by bfalacerda** [comment]
yep, i'll do it tomorrow, since i'm going on holidays friday
