### ISSUE TITLE
ImportError:  No module named smach

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/autonomous_patrolling#34]
I am struggling to launch the waypoint_patroller due to an import error for the smach module. ros-groovy-executive-smach is installed on the system and $ROS_PACKAGE_PATH should be fine (/opt/strands/strands_catkin_ws/src:/opt/ros/groovy/share:/opt/ros/groovy/stacks).

$ roslaunch waypoint_patroller long_term_patroller.launch waypoints:=/localhome/strands/2013_08_08_09_10_24waypoints.csv

Traceback (most recent call last):
  File "/opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/scripts/long_term_patroller.py", line 7, in <module>
    import smach
ImportError: No module named smach
[patroller-1] process has died [pid 790, exit code 1, cmd /opt/strands/strands_catkin_ws/src/autonomous_patrolling/waypoint_patroller/scripts/long_term_patroller.py /localhome/strands/2013_08_08_09_10_24waypoints.csv true -1 __name:=patroller __log:=/localhome/strands/.ros/log/b505d222-fff3-11e2-a78f-6c8814462a8c/patroller-1.log].
log file: /localhome/strands/.ros/log/b505d222-fff3-11e2-a78f-6c8814462a8c/patroller-1*.log

**Comment by ToMadoRe** [comment]
I think it's solved... I just put the https://github.com/strands-project/executive_smach repository in my catkin workspace

**Comment by marc-hanheide** [comment]
Just a comment: Did you follow the instruction in https://github.com/strands-project/strands_systems/blob/master/README.md ? If you simply install desktop-full or scitos-full as described in step 6, you'll always have everything you need in the right version!

**Comment by cdondrup** [comment]
Yesterday he said he did do it, but I guess it has been a while ago and he may have forgotten merge the .yaml file into the wstool workspace. In that case he would not have downloaded the executive_smach with an wstool update. I don't know if this might be the problem but please always follow the instructions: https://github.com/strands-project/strands_systems/blob/master/README.md#update-the-stable-installation and update regularly.
