### ISSUE TITLE
Recovery behaviour for docking failure

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#40]
We have seen cases where docking has failed. This should be detected and either retried in different ways, or a request made for human assistance.

**Comment by gestom** [comment]
Do you know the reason why docking failed ? A crash ? Timeout ?

**Comment by hawesie** [comment]
I'm not sure, as I haven't seen cases myself, only heard second hand reports. We're working on capturing more info from runs to answer these questions.

**Comment by bfalacerda** [comment]
The failures I saw were due to the robot getting too close to the station, and then bumping into it when it turns and tries to align itself with the marker.

**Comment by gestom** [comment]
Improved  numerical stability of eigenvector calculation during the circle localization calculation. 
Also, the charging re-attempts to dock several times until the timeout runs off. According to BHAM and KTH, the autonomous charging works reliably now.
