### ISSUE TITLE
Recovery behaviour for bumper

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#41]
When the bumper is pressed and not released (e.g. the robot is stuck on a table leg, as just happened here) there is no possibility for software recovery as the motors are off. We need to detect this has happened and general a cry for help via some medium (perhaps on the screen too).

**Comment by bfalacerda** [comment]
The bumper recovery currently gives up after 5 unsuccessful tries to restart the motors, so the detection part is basically done - it only fails to restart if the bumper is pressed.

We can use https://github.com/strands-project/strands_hri/tree/master/ros_mary_tts for the crying, its just a question of adding an extra state.

**Comment by hawesie** [comment]
Please can you switch the motors into free run when in the recovery behaviour? This means that the robot is easier to push around.

**Comment by bfalacerda** [comment]
Already done :)

**Comment by hawesie** [comment]
I thought I'd heard about this before. 

@mzillich do you want to just check this works on your robot then close this issue if you're happy?

**Comment by bfalacerda** [comment]
I left the issue open until now because we still don't have an on screen help message, only speaking.

**Comment by hawesie** [comment]
Ah, ok, I shall try to look at the GUI stuff a bit more this week.

**Comment by hawesie** [comment]
The robot doesn't currently switch to free run when it's asking for help on a bumper press. Is that code in yet?

**Comment by bfalacerda** [comment]
as we saw, there's a small bug and sometimes it doesn't, but most of the time it does. The next version will correct the bug

 However, while the bumper is pressed, even though free run appears an on, the motors continue enabled until the bumper is released and I don't think we can do anything about it

**Comment by bfalacerda** [comment]
closing solved old issues
