### ISSUE TITLE
PTU "waypoints" 

### ISSUE THREAD

**Issue by RaresAmbrus** [strands-project/autonomous_patrolling#47]
Hi guys,

I want to add functionality to the waypoint patroller & recorder to allow, in addition to moving the base, the control of the PTU. The goal being that during autonomous data collection runs, I want the robot to enter an office and pan and tilt the xtion to cover and record as much of the surroundings as possible. 

I just want to double check that no-one has started working on this to avoid work duplication.

Cheers,
Rares

**Comment by bfalacerda** [comment]
As far as I know, no one is working on that

**Comment by Jailander** [comment]
Hi, 
I was going to start working on the same functionality, but I would like to know what is the status of your work, I was thinking it should be implemented as an action server that you can call when you reach a waypoint, is this how you were planning on doing it or did you have any other idea.

cheers
Jaime

**Comment by bfalacerda** [comment]
Implementing it as an action server is the best way to then integrate the functionality on the patroller state machine. I think the functionality itself should be implemented in another repo (scitos_apps?), since it is something that is not  specific to the patroller.

**Comment by Jailander** [comment]
Hi Bruno,

I was implementing it in the Scitos_3D_mapping repo, Do you think that is a good place for it?

**Comment by bfalacerda** [comment]
yes, fair enough i guess

**Comment by RaresAmbrus** [comment]
Hey, I've already added an action server for the ptu in sctios_apps. We're currently integrating it with the compression stuff as well and adding it to the long term patroller. I think we'll merge back to the main repo early next week, maybe Tuesday.

**Comment by RaresAmbrus** [comment]
Oh I've also modified the waypoint recorder to record waypoints with PTZ info. I'll merge that as well next week.

**Comment by Jailander** [comment]
Hi that is great, Thanks a lot

**Comment by bfalacerda** [comment]
closing issues I think look solved to clean the repo's issue list. Please reopen if you fell further discussion is needed
