### ISSUE TITLE
/robot_pose topic is empty

### ISSUE THREAD

**Issue by ghost** [strands-project/autonomous_patrolling#53]
We were just trying to save new waypoints, however we are unable to create waypoints with the A button. We narrowed it down to the fact that nothing is published on the robot_pose topic and thus points are never saved. I can understand why @gestom changed this in #46, however we are wondering how to get this to run.

Any help is much appreciated!

**Comment by nilsbore** [comment]
Try to run the republish_robot_pose.py in scitos_utils.

**Comment by ghost** [comment]
@nilsbore thank you, this indeed fixes it, but I don't really see the point, as it just republishes the amcl localization at the same rate? I can't see the 10Hz that were mentioned in #46

**Comment by nilsbore** [comment]
Yeah, it's a bit of a mess to use since you have to wait for the next update until it stores the next waypoint.

**Comment by Jailander** [comment]
Hi, the amcl_pose is only updated when the robot position has changed, so if you reach a position and then press the A button it will wait for the next amcl_pose which will arrive after the robot has moved, so it is not in the same position you pressed the button. the replublisher keeps publishing the amcl_pose at a fixed rate so once you pressed the button a topic with the last position received from amcl which should be close to your current position will arrive in at most 0.1s

**Comment by cdondrup** [comment]
This is what should be running: http://wiki.ros.org/robot_pose_publisher
Not the republisher because that does nothing.

**Comment by hawesie** [comment]
Shouldn't this all be in a launch file? Is the documentation up to date such that the correct launch file is indicated?

**Comment by hawesie** [comment]
I'm hoping @cburbridge will also ensure everything is documented for launching once v2 of the patroller (#55) becomes master.

**Comment by cdondrup** [comment]
I am not aware of having to start anything specific to have the robot_pose_publisher running.

**Comment by ghost** [comment]
Hmmm, maybe I was a bit premature in adding it into the readme, however for
us it didn't work if we only used scitos_bringup and the waypoint recorder.

**Comment by bfalacerda** [comment]
I tested it now and also needed to run `rosrun robot_pose_publisher robot_pose_publisher` to get the waypoints recorded. I'm not aware of the last changes done here, but since it looks like this is really needed, we should add it to the waypoint_recorder launch file. Am I missing something?

**Comment by nilsbore** [comment]
We also needed to do that.
