### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by cburbridge** [strands-project/autonomous_patrolling#55]
An updated version of the waypoint patroller is in the v2_devel branch. Ideally I'd like to move this to master and move master to v1. The updated version includes the logging to the database, and provides a clean interface for reusing parts with other smach based state machines. 

It does not have the logging of images at the waypoints as recently added by @nilsbore  @RaresAmbrus ... Would either of you mind looking over it to see how we could add that to this version? 

Is there anything else missing from V2 that was in V1? @BFALacerda , is it ok to make v2_devel the master?

**Comment by bfalacerda** [comment]
The image logging is the only thing missing. I agree with making v2_devel the master

**Comment by nilsbore** [comment]
Me and @RaresAmbrus can have a look at integrating the logging tomorrow.

**Comment by cburbridge** [comment]
Ok I merged into v2_devel into Master, and added a tag for v1. I added a waypoint csv -> db utility to allow converting of waypoints as stored using the waypoint recorder. I will open an issue to update the recorder to store directly into the db.
