### ISSUE TITLE
Autonomomous patrolling not working for us.

### ISSUE THREAD

**Issue by ghost** [strands-project/autonomous_patrolling#61]
I left the robot of the charging station tonight to make sure it wanted to charge. The battery was indeed very empty this morning, so I tried to run the V1 patroller. This would directly try to charge, but it would spam a lot of information on the screen, including "stuck on carpet" and "going to charging station". Then it would pretty much get stuck, move back and forth a few cm, but never go back to the first waypoint. Upon killing the patroller, it would move to the charging station, but obviously it would not dock. 

We updated to V2, got the datacenter running and put the waypoints in the database. Upon running the patroller again, it would print the following in an, what I guess to be, endless loop:

[INFO] [WallTime: 1381406788.139132] Preempt requested on action 'move_base'
[INFO] [WallTime: 1381406788.139583] Preempt on action 'move_base' cancelling goal: 
target_pose: 
  header: 
    seq: 0
    stamp: 
      secs: 1381406788
      nsecs: 77442884
    frame_id: /map
  pose: 
    position: 
      x: -0.147166
      y: -2.15159
      z: -1.04083e-17
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.723288
      w: 0.690546
[INFO] [WallTime: 1381406788.140292] Concurrent state 'BUMPER_MONITOR' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1381406788.144584] Concurrent state 'STUCK_ON_CARPET_MONITOR' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1381406788.178793] State machine terminating 'MOVE_BASE':'preempted':'preempted'
[INFO] [WallTime: 1381406788.179615] Concurrent state 'MOVE_BASE_SM' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1381406788.180380] Concurrent Outcomes: {'BUMPER_MONITOR': 'preempted', 'MOVE_BASE_SM': 'preempted', 'STUCK_ON_CARPET_MONITOR': 'preempted', 'BATTERY_MONITOR': 'invalid'}
[INFO] [WallTime: 1381406788.180788] State machine terminating 'MONITORED_MOVE_BASE':'battery_low':'battery_low'
[INFO] [WallTime: 1381406788.181067] State machine transitioning 'GO_TO_CHARGING_STATION':'battery_low'-->'GO_TO_CHARGING_STATION'
[INFO] [WallTime: 1381406788.181762] State machine starting in initial state 'MONITORED_MOVE_BASE' with userdata: 
    ['goal_pose', 'going_to_charge']
[INFO] [WallTime: 1381406788.182092] Concurrence starting with userdata: 
    ['goal_pose', 'going_to_charge']
[INFO] [WallTime: 1381406788.185561] State machine starting in initial state 'MOVE_BASE' with userdata: 
    ['goal_pose']
[INFO] [WallTime: 1381406788.239632] Concurrent state 'BATTERY_MONITOR' returned outcome 'invalid' on termination.

The rest of the behavious is very much the same. Sometimes it stutters a bit forward and backwards, but it never actually moves. Upon killing it, it sometimes indeed moves back to the charging station.

Did we do something wrong, or did we miss something? Also we noticed that when running roslaunch scitos_docking charging.launch, it doesn't work, but instead we need to use rosrun scitos_docking visual_charging.

**Comment by bfalacerda** [comment]
How low was the battery level? It looks like it was less than 20%, which in fact is VERY_LOW. I added this threshold so we can eventually use it as a "panic" trigger, where the robot immediately asks for human assistance (so we guarantee that the batteries never get completely emptied). However, that is not implemented yet, and the GO_TO_CHARGING_STATION state continuously transitions to itself, creating the infinite loop you witnessed. All the info printed to the screen is normal, it's just preempting the monitor states when the concurrence container that has them terminates.

If you want to test the docking behaviour, you can use the dynamic reconfiguration of these parameters by running `rosrun rqt_reconfigure rqt_reconfigure`. 

We also cannot use `roslaunch scitos_docking charging.launch`, it has to do with the remapping  from cmd_vel to cmd_vel_mux, I'll open an issue about it.

**Comment by ghost** [comment]
@BFALacerda Thank you for the explanation, this does indeed explain the situation.
