### ISSUE TITLE
patches coming soon

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/autonomous_patrolling#68]
I've been promising some small changes in different issues so I'll just list them together here:
- [x] Disable move_base's recovery rotation behaviour and add an explicit call to clear the costmap in the move_base recovery state
- [x] Allow for dynamic reconfiguration of the max move base fails parameter (and other parameters that are not reconfigurable)
- [x] Add a new state for the state machine to jump to when the battery level is VERY_LOW. Since we have  https://github.com/strands-project/strands_utils/tree/master/battery_check, I think this state will be just standing still
- [x] Use undocking action to get out of the charging station
- [x] Call for help plus free run when move base fails too many times
- [ ] "smarter" start up, as suggested in #72
- [x] put robot on free run when pause service is called

Please add other small enhancements that you think should be done here

**Comment by hawesie** [comment]
As discussed in the marathon Skype today, we need a call for help _plus free run_ when move base fails too many times.

**Comment by bfalacerda** [comment]
How urgent are these things? It's pretty hard to test them without a robot, so if we want them ready fast I would need  someone testing them in  another site. The other option is waiting for Bob to come back

**Comment by bfalacerda** [comment]
closing solved old issues
