### ISSUE TITLE
rumblepad control for simulation

### ISSUE THREAD

**Issue by cdondrup** [strands-project/autonomous_patrolling#7]
With the new features like emergency stop and re-enabling the motors after a bump the rumblepad_control package needs the scitos_mria package as a dependency because of the provided services. It might be nice to make these new features optional to be able to compile the rumbepad_control without scitos_mira for use with the simulator.

**Comment by cburbridge** [comment]
You should use scitos_msgs as dependency, then there should be no problem compiling for the simulator. Pressing buttons wont that call the services wont work of course...so either check the service is available first or i could implement the service is simulation?

**Comment by cdondrup** [comment]
Thanks for the tip. I will implement that for the pad control. I think there is no need to have these services in simulation as long as we do not have a simulated bumper.
