### ISSUE TITLE
free run on pause

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#73]
For dealing with a robot in a bad position, I'd like to switch the robot into free run mode when it's paused. There will be a button on the GUI to pause it, so I could also trigger free run from the button, but this would be GUI specific. Perhaps it would be better for the patroller to switch to free run on pause so that the behaviour is consistent across all GUIs/interactions. What do people think?

**Comment by bfalacerda** [comment]
We can add it to the pause service, makes sense. 
Just a sidenote - It won't work for the gamepad based pause because there we are assuming control via teleop.

Another small thing to do when Bob gets back, this is the kind of change that is pretty hard to test without the robot

**Comment by bfalacerda** [comment]
closing solved old issues
