### ISSUE TITLE
RVIZ not working !

### ISSUE THREAD

**Issue by OMARI1988** [strands-project/autonomous_patrolling#77]
Hi,

I am trying to start the map-saver with the rumblepad, the robot is moving and everything seems to be working. but when I start the rosrun rviz rviz I get this error.

strands@strands-Mi956:~$ rosrun rviz rviz 
[ INFO] [1384182771.425568795]: rviz version 1.9.32
[ INFO] [1384182771.425649129]: compiled against OGRE version 1.7.4 (Cthugha)
[ INFO] [1384182771.746925125]: OpenGl version: 3 (GLSL 1.3).
Illegal instruction (core dumped)

I tried rebooting but still its not working ? any ideas !

Muhannad

**Comment by nilsbore** [comment]
I get this error both on the robot and my computer. Usually it works after a couple of times so try to do it ten times or so.

**Comment by OMARI1988** [comment]
I don't think this is the case, I tried many many times and it doesn't work.

when I run the command the rviz window appear for a sec and then the error
comes !

**Comment by bfalacerda** [comment]
try:
1. open rviz without anything else running
2. remove everything that is being displayed
3. save that "blank" rviz configuration
4. quit and re run rviz, this time with the patroller running also
5. if it opens, add the stuff you want to display again

**Comment by OMARI1988** [comment]
I can't even open rviz alone without anything, the same problem occurs !

**Comment by marc-hanheide** [comment]
What graphic card are you trying on? I had a similar issue on an Intel Grahics once

**Comment by OMARI1988** [comment]
I will check tomorrow morning and let you know. It might be the problem
because it never worked, not even once !

**Comment by OMARI1988** [comment]
Hi Marc,

I have this one,

00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core
Processor Family Integrated Graphics Controller (rev 09)

# 

```
   description: VGA compatible controller
   product: 2nd Generation Core Processor Family Integrated Graphics
```

Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:57 memory:f7400000-f77fffff memory:e0000000-efffffff
iopor

**Comment by marc-hanheide** [comment]
yeah... Intel one... I had a similar problem with that one. Best recommendation I can give: Use a machine with a proper graphics card. Or, try to disable any 3D effects on your desktop (e.g. not running compiz, run gnome 2D). That did the trick for me, but no guarantees.

**Comment by OMARI1988** [comment]
I am trying it on the robot, also I tried the gnome 2D and it didn't work.

Which driver your robot have ?

**Comment by marc-hanheide** [comment]
OK, that's weird. You have Ubuntu 12.04 64bit installed? I have seen the problem on the robot as well, but only rarely... And restarting once always fixed it for me. I'm pretty clueless then, I have to admit. Maybe @cdondrup @gestom @Jailander who use the robot much more than I do have an idea. The only other idea I have is to delete `~/.rviz` and try again...

**Comment by cdondrup** [comment]
As @marc-hanheide said, this also happens on Linda but after a few (normally 1-4) restarts it works as intended. However, a while ago I noticed that other applications using Qt might influence that. I was testing a Qt based programme and could not start rviz while this was running. I had to close the other programme run rviz and then start it again. But in principle it should work if nothing else is running.
I also just tried it on my laptop which doesn't have a graphics card either (VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller) and I do run compiz so I have no real clue what could be wrong here.

**Comment by RaresAmbrus** [comment]
On my machine I get the following information when starting rviz:

[ INFO] [1384340044.306906173]: rviz version 1.9.30
[ INFO] [1384340044.307059937]: compiled against OGRE version 1.7.4 (Cthugha)
[ INFO] [1384340045.465006645]: OpenGl version: 4.2 (GLSL 4.2).

Maybe you should try updating your OpenGl version?

**Comment by OMARI1988** [comment]
Ok will try that, thanks.

**Comment by OMARI1988** [comment]
I found that in the system tools >> system settings >> Details >> I have no
graphic driver ! it's just empty ..

Also I tried to install the latest opengl 4.4 and I get an error which says
that the graphic driver is not compatible

can some one advice,

Muhannad

**Comment by OMARI1988** [comment]
Can someone please let me know what is the correct graphic card driver and
how to install it !

**Comment by marc-hanheide** [comment]
Is it now working? Please share the fix.

**Comment by OMARI1988** [comment]
Yup its working, I partitioned the hard-drive and reinstalled everything
from the beginning :)
