### ISSUE TITLE
Integrate robot GUI into long-term patroller

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#78]
I've just/finally committed a first version of the GUI to run on the robot screen. Please see [the README](https://github.com/strands-project/strands_ui/blob/master/README.md) for information on how to use it. It is now ready for a first pass integration into the patroller, so please can you take a look @BFALacerda? It is very much a beta, so please report bugs and request features as appropriate. I'll be listening out for questions too.

**Comment by bfalacerda** [comment]
closing solved old issues
