### ISSUE TITLE
Missing file in patroller: ap_msgs/srv/HelpOffered.srv does not exist

### ISSUE THREAD

**Issue by hawesie** [strands-project/autonomous_patrolling#82]
```
-- +++ processing catkin package: 'ap_msgs'
-- ==> add_subdirectory(autonomous_patrolling/ap_msgs)
CMake Error at /opt/ros/groovy/share/catkin/cmake/assert.cmake:20 (message):


  Assertion failed: file
  '/Users/nah/code/strands_catkin_ws/src/autonomous_patrolling/ap_msgs/srv/HelpOffered.srv'
  does not exist.  Message: service file not found
```

Also, if you're just offering empty services, you can just register them as the type `std_srvs/Empty` rather than defining your own new empty type.

**Comment by hawesie** [comment]
In fact, I'll update the code in this way now as I have to do it for the local fix anyway.

**Comment by bfalacerda** [comment]
Ok, I guess I forgot to merge that file for some reason. Didn't know about those empty type services, they are convenient
