### ISSUE TITLE
waypoint patroller not working any more

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/autonomous_patrolling#87]
For some unknown reason, our robot does not want to patrol any more when starting the waypoint_patroller. 
It can navigate to goals sent in RVIZ. Not sure if the points are in the database (how can I check that?). Any name for the argument waypoints gives the same message... And yes, I did insert the points before with the insert_in_db.py script:

```
process[nav_monitor-3]: started with pid [8623]
Ready to speak.
Voices: 
 -  dfki-spike-hsmm
 -  dfki-poppy-hsmm
 -  dfki-prudence-hsmm
 -  dfki-obadiah-hsmm
process[patroller-4]: started with pid [8707]
process[log_services-5]: started with pid [8715]
[INFO] [WallTime: 1384868476.066158] Executing waypoint_patroller with sequential point selection.
[INFO] [WallTime: 1384868476.066451] Executing waypoint_patroller with infinite iterations
 started in 31.217 s
```

**Comment by hawesie** [comment]
You need to launch the web server GUI stuff which the patroller requires:

```
HOST_IP=<my robot IP> roslaunch marathon_touch_gui marathon_gui_dependencies.launch 
```

**Comment by ToMadoRe** [comment]
Thanks, robot running again :)
